FROM node:16-alpine

RUN mkdir /app
WORKDIR /app

ADD package*.json ./

RUN apk add --update --no-cache python3 py3-pip make g++ && rm -rf /var/cache/apk/*

RUN npm install

COPY public /public

ADD index.html vite.config.js ./

EXPOSE 80

CMD ["npm", "run", "dev"]